guests=["abraham lincoln","dougles adams","terry prachet"]
print(guests[0].title()+" will you be so kind as to attend my party?")
print(guests[1].title()+" will you be so kind as to attend my party?")
print(guests[2].title()+" will you be so kind as to attend my party?")
print(guests[0].title()+" cant make it, invite ainstain insted")
guests[0]="albert ainstain"
print(guests[0].title()+" will you be so kind as to attend my party?")
print("I found a bigger table lets invite some more people")
guests.insert(0,"death")
guests.insert(2,"kino")
guests.append("miles morlas")
print(guests[0].upper()+" will you be so kind as to attend my party?")
print(guests[1].title()+" will you be so kind as to attend my party?")
print(guests[2].title()+" will you be so kind as to attend my party?")
print(guests[3].title()+" will you be so kind as to attend my party?")
print(guests[4].title()+" will you be so kind as to attend my party?")
print(guests[5].title()+" will you be so kind as to attend my party?")
print(" the table wont make it im afreid will have to cut this to 3 person event")
print(guests.pop()+ " Im afarid youre uninvited")
print(guests.pop()+ " Im afarid youre uninvited")
print(guests.pop()+ " Im afarid youre uninvited")
print(guests.pop()+ " Im afarid youre uninvited")
print(guests[0].upper()+" will you be so kind as to attend my party?")
print(guests[1].title()+" will you be so kind as to attend my party?")
print(guests)
del guests[0]
del guests[0]
print(guests)